### ISSUE TITLE
Contributor License Agreement

### ISSUE THREAD

**Issue by Phil0499** [mkoch227/ets2-mobile-route-advisor#18]
I tried to sign the Contributor License Agreement you made (at https://www.clahub.com/agreements/mkoch227/ets2-mobile-route-advisor/ ) but every time I get this message :

We're sorry, but something went wrong.

![capture](https://cloud.githubusercontent.com/assets/10819248/8145821/89962644-11e6-11e5-909d-d6f37e74f81c.PNG)

Any idea on how to fix it ?

**Comment by mkoch227** [comment]
Not sure, as I don't run CLAHub. It's had issues in the past as well, so don't worry about it for now.

**Comment by mkoch227** [comment]
Apparently I clicked twice on "close issue". Reclosing.
