### ISSUE TITLE
Promods 2.51

### ISSUE THREAD

**Issue by ColinShark** [mkoch227/ets2-mobile-route-advisor#188]
The [hosted promods map](https://github.com/mike-koch/ets2-mobile-route-advisor/tree/map-packs) is slightly outdated, being dated back to 4 years. [Promods 2.51 has been released a few weeks ago](https://www.promods.net/compat.php) and I'd love to use the updated map in this project. Would you be able to re-make the promods map with the current release?

<details>If you want I can send you over the archive of the promods mod for the purpose of making an updated map</details>

**Comment by meatlayer** [comment]
Need to wait for the new Iberia DLC, after which Promods will once again release a new version. 
And only then can start capturing current version of Promod. 
Approximately, the new DLC on ETS2 will be released sometime in early December 2020.

**Comment by ColinShark** [comment]
Ah well, fair enough. Thanks for the quick reply

**Comment by meatlayer** [comment]
Due to the fact that the [Iberia DLC will not be in this 2020 year](https://blog.scssoft.com/2020/11/the-good-news-and-mixed-news.html), and for the ATS DLC Colorado has already been released, I will try to release an update of the ATS map and possibly Promods in the near future.
