### ISSUE TITLE
BUG; 12h format not working.

### ISSUE THREAD

**Issue by Sokoloft** [mkoch227/ets2-mobile-route-advisor#190]
As the title says, 12h format isn't working. I've set it in the config.json.

`"timeFormat": "12h",`

EDIT; I failed to mention I'm on v1.40 beta currently. Maybe that could be the issue?

Thanks. Awesome skin/mod. Helps a lot.

**Comment by olakepro** [comment]
Nope, still not working, and this is an issue that been here way before 1.40. Let me know if you find a way to fix it.

**Comment by meatlayer** [comment]
I fixed this bug in my [fork](https://github.com/meatlayer/ets2-mobile-route-advisor/commit/fec32f0a4cd2914c555f39e30a6d9162c077f72d) ets2 mobile router advisor.

**Comment by Sokoloft** [comment]
My bad I should of closed this issue a while ago. Sadly I can't use your fork meatslayer due to it being a newer version. In my issue request there I transfer the map data from your fork to an older 3.x version and it works fine for me and the older truck mod I use. With that I'll close this.
