### ISSUE TITLE
Missing countries on the map

### ISSUE THREAD

**Issue by ZKillou** [mkoch227/ets2-mobile-route-advisor#191]
Hi, I have seen some countries are missing like Spain, Portugal, Turkey, Bulgaria, Romania and cities like Bayonne and Lacq and Corsica and Sardinia.

**Comment by meatlayer** [comment]
> 
> 
> Hi, I have seen some countries are missing like Spain, Portugal, Turkey, Bulgaria, Romania and cities like Bayonne and Lacq and Corsica and Sardinia.

This main repository has so far been abandoned by its author. I can offer to get an up-to-date version with the latest update of all DLC maps in [this repository](https://github.com/meatlayer/ets2-mobile-route-advisor).

**Comment by mike-koch** [comment]
It is indeed safe to say that I have been doing a poor job at maintaining this project.  Given that the telemetry server itself is no longer being maintained (to my knowledge), the fact that I don't play ETS2/ATS that much anymore, and me having other priorities at the moment, the motivation for me to work on this is fairly slim.

If there's a better backend to use for this skin (such as [JAGFx's solution](https://github.com/JAGFx/ets2-dashboard-skin) or something like [SIM Dashboard](https://www.stryder-it.de/simdashboard/ets2_ats)), I'd be up for porting over the skin to one of those solutions, as I know that I definitely do not have the time to maintain both this *and* the telemetry server itself.

**Comment by meatlayer** [comment]
> 
> 
> It is indeed safe to say that I have been doing a poor job at maintaining this project. Given that the telemetry server itself is no longer being maintained (to my knowledge), the fact that I don't play ETS2/ATS that much anymore, and me having other priorities at the moment, the motivation for me to work on this is fairly slim.
> 
> If there's a better backend to use for this skin (such as [JAGFx's solution](https://github.com/JAGFx/ets2-dashboard-skin) or something like [SIM Dashboard](https://www.stryder-it.de/simdashboard/ets2_ats)), I'd be up for porting over the skin to one of those solutions, as I know that I definitely do not have the time to maintain both this _and_ the telemetry server itself.

Anyway, despite the fact that I have not played ets2/ats for quite a long time, I will still try to support this project for some time. I think it can be very useful for fans of these games. Thank you for your contribution and that of other contributors.

**Comment by ZKillou** [comment]
Okay, thanks for your answers.
