### ISSUE TITLE
Weekday Strings

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/ets2-mobile-route-advisor#23]
Should weekdays stay as is (Monday, Tuesday, etc) or be shortened (Mon, Tue, etc)?  Also, should the strings be localized?

~~Another option is to look into possibly using `Date.prototype.toLocaleString()` which might be able to handle formatting as well as localization.~~
`Date.prototype.toLocaleString()` will always return the short date, and using the `options` parameter isn't supported by many browsers.  So it won't be used.

**Comment by denilsonsa** [comment]
Shorter weekday strings means shorter overlay text on the map, which will most likely look better and be less distracting. And it will be less likely it will wrap into two lines.

Long translated weekdays might take too much space, and force the layout to wrap in two lines, specially the top bar.

For such reasons, I believe all weekdays should be abbreviated.
