### ISSUE TITLE
Add config options for currency code

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/ets2-mobile-route-advisor#3]
In the `config.json`, add two new config options:
 - **currency code**: allow the user to enter their currency code to display the proper symbol on the screen. The telemetry SDK does not provide this information, so the user will need to enter this manually to update the Mobile Route Advisor.

_**TODO: Add list of currency codes supported in ETS2 and their cooresponding currency symbols to use as reference. There (hopefully) should be HTML codes for each currency code**_

**Comment by SirGuren** [comment]
@mkoch227, Exactly what am i supposed to add into the config.json file?

**Comment by mkoch227** [comment]
Nothing for now, as I need to also update the javascript source file. For now just replace `&euro;` with `&pound;` (as I stated earlier) to switch from euros to pounds

**Comment by SirGuren** [comment]
So there is no way of changing the amount displayed to the appropriate amount for pounds?

**Comment by mkoch227** [comment]
i thought the telemetry SDK returned the converted value....but i could be wrong. i'll have to double-check that.

**Comment by SirGuren** [comment]
@mkoch227, all that does it change the symbol to pounds. it does not change the amount shown. Is there a way to intercept and modify the output?

**Comment by SirGuren** [comment]
I tried:

function getDigitGroupedReward(income) {
	income = income * 0.75
}

**Comment by SirGuren** [comment]
Apparently changing:
data.digitGroupedReward = getDigitGroupedReward(data.jobIncome);
to:
data.digitGroupedReward = getDigitGroupedReward(data.jobIncome * 0.8);
doesn't work

**Comment by mkoch227** [comment]
Mobile Route Advisor now has a config parameter for currency code.
