### ISSUE TITLE
Update Site for 3.0.0 Release

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/ets2-mobile-route-advisor#38]
Update http://www.mikekoch.me/ets2-mobile-route-advisor for the 3.0.0 release

- [x] Updated screenshots (perhaps some sort of carousel on the tablet?)
- [x] ~~Pull latest release via GitHub API, rather than `_config.yml`~~
- [x] ~~Provide download for custom `ets2-telemetry-server`~~
- [x] Display list of translations via the GitHub API. API to call: `https://api.github.com/repos/mkoch227/ets2-mobile-route-advisor/contents?ref=i18n`

**Comment by raflix261** [comment]
I have a problem with the translation in the new version. In place of TimeRemaining does not change the values ​​translated.
![screenshot_3](https://cloud.githubusercontent.com/assets/8672101/10275838/fd593a04-6b4a-11e5-8483-0eb0cfbb6952.png)

**Comment by mkoch227** [comment]
@raflix261 , please create a separate issue for your problem, as this is not related to this current issue.
